eboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meeting.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

meeting/urls.py
from django.urls import path
from .views import MeetingsView,UpdateMeetingView, UpdateAgendaView, UpdateDocumentView, AgendasView,CreateAgendaView,CreateDocumentView, CreateMinutesView, UpdateMinutesView, DeleteAgendaView,DeleteDocumentView,DeleteMeetingView, CreateMeetingView

app_name="meeting"
urlpatterns = [
    path('', MeetingsView.as_view(), name='meeting_list'),
    path('add-board/', CreateMeetingView.as_view(), name='meeting_create'),
    path('<str:slug>/', AgendasView.as_view(), name='agenda_list'),
    path('<str:slug>/update-board/', UpdateMeetingView.as_view(), name='meeting_update'),
    path('<str:slug>/delete-board/', DeleteMeetingView.as_view(), name='meeting_delete'),
    path('<str:slug>/minutes/', CreateMinutesView.as_view(), name='minutes_page'),
    path('<str:slug>/agenda/', CreateAgendaView.as_view(), name='agenda_create'),
    path('<str:slug>/document/', CreateDocumentView.as_view(), name='document_create'),
    path('<str:meeting>/<str:slug>/update-minutes/', UpdateMinutesView.as_view(), name='minutes_update'),
    path('<str:meeting>/<str:slug>/update-agenda/', UpdateAgendaView.as_view(), name='agenda_update'),
    path('<str:meeting>/<str:slug>/update-document/', UpdateDocumentView.as_view(), name='document_update'),
    path('<str:meeting>/<str:slug>/delete-agenda/', DeleteAgendaView.as_view(), name='agenda_delete'),
    path('<str:meeting>/<str:slug>/delete-document/', DeleteDocumentView.as_view(), name='document_delete'),
]

meeting/models.py
from time import timezone
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify
from django.core import validators
from ckeditor.fields import RichTextField
from django.urls import reverse
# from django.utils.timezone import now, timezone,datetime
# import datetime
# 
# def validate_date(date):
#     if date < timezone.now().date():
#         raise ValidationError("Date cannot be in the past")

class Meeting(models.Model):
    name = models.CharField(max_length=50)
    theme = models.CharField(max_length=500)
    dateScheduled = models.DateField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=60, blank=True)

    def __str__(self):
        return f'{self.name} id {self.pk} '



    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.name}-{self.dateCreated}')
        super(Meeting, self).save(*args, **kwargs)


    class Meta:
        ordering = ["-dateCreated"]


class Agenda(models.Model):
    title = models.CharField(max_length=50)
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, related_name='agendas')
    dateCreated = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=60, blank=True)

    def __str__(self):
        return f'Agenda of {self.meeting.name} meeting id {self.pk}'

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.title}-{self.dateCreated}')
        super(Agenda, self).save(*args, **kwargs)

    class Meta:
        ordering = ["dateCreated"]

    def get_absolute_url(self):
        return reverse('meeting:agenda_list', kwargs={'slug':self.meeting.slug})

class Document(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE , related_name='documents')
    docname = models.CharField(max_length=30)
    doc = models.FileField(upload_to='documents', max_length=50)
    dateuploaded = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=60, blank=True)

    def __str__(self):
        return f'Documents of {self.meeting.name} - {self.pk}'

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.meeting.name}-{self.docname}-{self.dateuploaded}')
        super(Document, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-dateuploaded"]

    def get_absolute_url(self):
        return reverse('meeting:agenda_list', kwargs={'slug':self.meeting.slug})


class Minutes(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE ,related_name='minutes')
    textfield = RichTextField(null=True, blank=True)
    slug = models.SlugField(max_length=60, blank=True)

    def __str__(self):
        return f'Minutes of {self.meeting.name} meeting id {self.meeting.pk}'

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.meeting.name}-{self.pk}')
        super(Minutes, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('meeting:agenda_list', kwargs={'slug':self.meeting.slug})

    

meeting/forms.py
from django import forms
from .models import Minutes, Meeting, Agenda, Document

class Minuteform(forms.ModelForm):
    class Meta:
        model = Minutes
        fields = ['textfield',]

        widgets = {'textfield':forms.Textarea()}


class Meetingform(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ['name','theme', 'dateScheduled']

        widgets = {
            'dateScheduled': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'date'
                       }),
        }

class AgendaForm(forms.ModelForm):
    class Meta:
        model = Agenda
        fields = ['title',]

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['docname','doc',]

meeting/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from .models import Meeting,Minutes,Document,Agenda
from .filters import MeetingFilter
from.forms import Minuteform, Meetingform, AgendaForm, DocumentForm

# View for meeting lists
class MeetingsView(ListView):
    model = Meeting
    template_name = 'meeting/meeting_list.html'

    def get_queryset(self):
        qs=self.model.objects.all()
        meetings = MeetingFilter(self.request.GET, queryset=qs)
        return meetings.qs

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context['meetings']=MeetingFilter(self.request.GET, queryset=self.get_queryset())
        return context

# view for displaying agendas and documents
class AgendasView(DetailView):
    model = Meeting
    context_object_name = 'meetings'
    template_name = 'meeting/agenda_docs.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['agenda_count'] = Agenda.objects.filter(meeting=context['meetings']).count()
        context['doc_count'] = Document.objects.filter(meeting=context['meetings']).count()
        context['mint'] = Minutes.objects.filter(meeting=context['meetings'])
        return context


# View for Creating Agendas in a meeting in the UI
class CreateAgendaView(CreateView):
    form_class = AgendaForm
    model = Meeting
    template_name = 'meeting/agenda_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('meeting:agenda_list', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.meeting = self.object
        fm.save()
        return super(CreateAgendaView, self).form_valid(form)

# View for Creating Documents in a meeting in the UI
class CreateDocumentView(CreateView):
    form_class = DocumentForm
    model = Meeting
    template_name = 'meeting/document_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('meeting:agenda_list', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.meeting = self.object
        fm.save()
        return super(CreateDocumentView, self).form_valid(form)


#view for updating agenda
class UpdateAgendaView(UpdateView):
    model = Agenda
    template_name = 'meeting/edit_agenda.html'
    fields = ['title',]


class UpdateDocumentView(UpdateView):
    model = Document
    template_name = 'meeting/edit_document.html'
    fields = ['docname','doc',]

# view for deleting agendas in the ui
class DeleteAgendaView(DeleteView):
    model = Agenda
    template_name = 'meeting/agenda_delete.html'
    success_url = reverse_lazy('meeting:agenda_list')

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('meeting:agenda_list', kwargs={'slug': self.object.meeting.slug})

# view for deleting in the ui
class DeleteDocumentView(DeleteView):
    model = Document
    template_name = 'meeting/document_delete.html'
    success_url = reverse_lazy('meeting:agenda_list')

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('meeting:agenda_list', kwargs={'slug': self.object.meeting.slug})


# view for creating minutes
class CreateMinutesView(CreateView):
    form_class = Minuteform
    model = Meeting
    template_name = 'meeting/minutes_view.html'

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('meeting:agenda_list',kwargs={'slug':self.object.slug})


    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.meeting = self.object
        fm.save()
        return super(CreateMinutesView, self).form_valid(form)

# view for updating minutes
class UpdateMinutesView(UpdateView):
    model = Minutes
    template_name = 'meeting/edit_minutes.html'
    fields = ['textfield',]
    # success_url = reverse_lazy('meeting:agenda_list')


# View for Creating meetings in the UI
class CreateMeetingView(CreateView):
    form_class = Meetingform
    model = Meeting
    template_name = 'meeting/meeting_create.html'
    success_url = reverse_lazy('meeting:meeting_list')

# View for Creating meetings in the UI
class UpdateMeetingView(UpdateView):
    fields = ['name','theme', 'dateScheduled']
    model = Meeting
    template_name = 'meeting/meeting_update.html'
    success_url = reverse_lazy('meeting:meeting_list')


# View for deleting meetings in the UI
class DeleteMeetingView(DeleteView):
    model = Meeting
    template_name = 'meeting/meeting_delete.html'
    success_url = reverse_lazy('meeting:meeting_list')

meeting/templates/meeting/agenda_create.html
{% extends "index.html" %}
{% block title %}Create agenda{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

</style>

<div class="container form-container">
    <h3 class="mt-3 mb-3">Create new Agenda</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">add agenda</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/agenda_delete.html
{% extends "index.html" %}
{% block title %}Delete agenda{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    display: flex;
    flex-direction: column;
    justify-content:center;
    align-items: center;
    }

    .btnu{
    margin: auto;
    width: 10%;
    display: flex;
    justify-content: center;
    }

    label{
    display: none;
    }

</style>

<div class="container form-container">
    <h3 class="text-center">Delete {{ object.name }}?</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mt-3 btnu"><i class="bi bi-trash"></i></button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/agenda_docs.html
{% extends "index.html" %}
{% block title %}{{ object.name }}{% endblock %}

{% block navbutton %}
<style>
.add-link{
display: flex;
align-items: center;
}

.agenda-navlinks{
display: flex;
}

@media(max-width: 760px){
.add-board{
font-size: 10px;
}
}
</style>
<div class="agenda-navlinks">
    <a class="navbar-brand text-light btn btn-success add-link" href="{% url 'meeting:agenda_create' slug=object.slug %}"><i class="bi bi-plus-square"></i><small class="text-dark add-board">agenda</small></a>
    <a class="navbar-brand text-light btn btn-success add-link" href="{% url 'meeting:document_create' slug=object.slug %}"><i class="bi bi-plus-square"></i><small class="text-dark add-board">documents</small></a>
</div>
{% endblock %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<style>
.agenda-page{
margin-top: 80px;
}
.container-holder,
.header{
display: flex;
justify-content: space-between;
margin-top: 20px;
align-items: center;
}
.agenda{
flex: 2;
}

.agenda,
.documents{
border: 1px solid #ccc;
}

.documents{
display: flex;
flex-direction: column;
flex: 1;
margin-left: 10px;
}
.img-download{
padding-right: 5px;
}
.documents img,.img-download{
height : 50px;
width : 50px;
border-radius: 10px;
}

.documents a{
text-decoration: none;
margin-bottom: 20px;
margin-top: 10px;
display: flex;
align-items: center;
padding-left: 5px;
}
.documents a:hover{
text-decoration: underline;
}

.docname{
margin-left: 10px;
}

.count{
margin-left: 5px;
font-weight: 200;
font-style: italics;
}

.title-wrapper{
display: flex;
align-items: center;
background: teal;
color: #fff;
padding: 15px;
}
.bi{
padding-right: 5px;
}

.agenda-list{
display: flex;
justify-content: space-between;
font-size: 25px;
font-weight: 400;
padding-bottom: 10px;
letter-spacing: 1.5px;
}

.agenda-li{
font-size: 25px;
}

.doc-holder{
display: flex;
justify-content: space-between;
align-items: center;
}
.del-editicons{
display: flex;
}

@media(max-width: 760px){
.container-holder{
display:flex;
flex-direction: column;
}
.agenda-list,.agenda-li{
font-size: 18px;

}
.documents, .agenda{
width: 100%;
margin: 0;
}

.documents{
margin-top: 20px;
}
}
</style>
<section class="agenda-page">
    <div class="container">
        <div class="header mt-3 mb-3">
            <h2 class="text-black ">Welcome to <span class="text-secondary">{{ object.name }}</span></h2>
            {% if mint %}
                {% for minutes in meetings.minutes.all %}
             <a class="btn btn-success d-flex align-items-center" href="{% url 'meeting:minutes_update' slug=minutes.slug meeting=meetings.slug %}"><i class="bi bi-pencil-square"></i>Edit Minutes</a>
                {% endfor %}
            {% else %}
                <a class="btn btn-primary d-flex align-items-center" href="{% url 'meeting:minutes_page' slug=object.slug %}">Take Minutes</a>
            {% endif %}
        </div>

        <div class="container-holder">
            <div class="agenda">
                <h3 class="title-wrapper"><img class="img-download" src="{% static 'files/images/agenda.jpg' %}"/>Agendas for today's meeting<span class="count">({{agenda_count}})</span></h3>
                <ol>
                {% for agenda in meetings.agendas.all %}
                    <li class="agenda-li">
                        <div class="agenda-list">
                            {{ agenda.title }}
                            <div class="del-editicons">
                                <span><a class="d-flex align-items-center" href="{% url 'meeting:agenda_update' slug=agenda.slug meeting=meetings.slug %}"><i class="bi bi-pencil-square"></i></a></span>
                                <span><a class="d-flex align-items-center" href="{% url 'meeting:agenda_delete' slug=agenda.slug meeting=meetings.slug %}"><i style="color: red;" class="bi bi-trash"></i></a></span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
                </ol>
            </div>

    <!--        Documents section-->
            <div class="documents">
                <h3 class="title-wrapper"><img class="img-download" src="{% static 'files/images/document.png' %}"/>Documents<span class="count">({{doc_count}})</span></h3>
                {% for document in meetings.documents.all %}
                <div class="doc-holder">
                    <a href="{{document.doc.url}}" target="_blank">
                        <img src="{% static 'files/images/docimg.png' %}" />
                        <p class="d-flex pt-2 docname">{{ document.docname }}</p>
                    </a>
                    <div class="del-editicons">
                        <span><a class="d-flex align-items-center" href="{% url 'meeting:document_update' slug=document.slug meeting=meetings.slug %}"><i class="bi bi-pencil-square"></i></a></span>
                        <span><a class="d-flex align-items-center" href="{% url 'meeting:document_delete' slug=document.slug meeting=meetings.slug %}"><i style="color: red;" class="bi bi-trash"></i></a></span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>


</section>

{% endblock %}

meeting/templates/meeting/document_create.html
{% extends "index.html" %}
{% block title %}Create doc{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

</style>

<div class="container form-container">
    <h3 class="mt-3 mb-3">Create new document</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">add document</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/document_delete.html
{% extends "index.html" %}
{% block title %}Delete Doc{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    display: flex;
    flex-direction: column;
    justify-content:center;
    align-items: center;
    }

    .btnu{
    margin: auto;
    width: 10%;
    display: flex;
    justify-content: center;
    }

    label{
    display: none;
    }

</style>

<div class="container form-container">
    <h3 class="text-center">Delete {{ object.name }}?</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mt-3 btnu"><i class="bi bi-trash"></i></button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/edit_agenda.html
{% extends "index.html" %}
{% block title %}Edit Agenda{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

</style>

<div class="container form-container">
    <h3 class="mt-3 mb-3">Update agenda</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">save agenda changes</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/edit_document.html
{% extends "index.html" %}
{% block title %}Edit Doc{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

</style>

<div class="container form-container">
    <h3 class="mt-3 mb-3">Edit document</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">save doc changes</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/edit_minutes.html
{% extends "index.html" %}
{% block title %}Edit Minutes{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 40%;
    display: flex;
    justify-content: center;
    }

    label{
    display: none;
    }

</style>

<div class="container form-container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">edit</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/meeting_create.html
{% extends "index.html" %}
{% block title %}Create Meeting{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

</style>

<div class="container form-container">
    <h3 class="mt-3 mb-3">Create new meeting</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">add meeting</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/meeting_delete.html
{% extends "index.html" %}
{% block title %}Delete Meeting{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    display: flex;
    flex-direction: column;
    justify-content:center;
    align-items: center;
    }

    .btnu{
    margin: auto;
    width: 10%;
    display: flex;
    justify-content: center;
    }

    label{
    display: none;
    }

</style>

<div class="container form-container">
    <h3 class="text-center">Delete {{ object.name }}?</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mt-3 btnu"><i class="bi bi-trash"></i></button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/meeting_list.html
{% extends "index.html" %}
{% block title %}Meetings{% endblock %}
{% block navbutton %}
<style>
    .add-board{
    margin-left: 5px;
    }
    .add-link{
display: flex;
align-items: center;
}

    @media(max-width: 760px){
    .add-board{
    font-size: 12px;
    }
    }
</style>
<a class="navbar-brand text-light btn btn-success add-link" href="{% url 'meeting:meeting_create' %}"><i class="bi bi-plus-square"></i><small class="text-dark add-board">Add Board</small></a>{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<style>
.meeting-holder{
margin-top: 80px;
display: flex;
flex-direction: column;
justify-contents: center;
border: 1px solid #ccc;
padding: 10px;
max-width: 550px;
border-radius: 5px;
}
.meeting-header{
display: flex;
justify-content: space-between;
}

.meeting-card{
margin-top: 5px;
width: 100%;
padding: 20px;
border-bottom: 1px solid #ccc;
}
.meeting-card-holder{
height: 100vh;
overflow-y: scroll;
}
}
.date-tag{
display: flex;
justify-content: space-between;
}

.search{
display: flex
padding: 15px;
width: 60%;
margin: auto;
}

form{
display: flex;
}

label{
display: none;
}
.del-editicons{
display: flex;
}
</style>
<section>
    <div class="container meeting-holder">
        <h1 class="text-center" >Choose a meeting to join</h1>
        <div class="search">
            <form method="get" id="searchForm">
                {{ meetings.form|crispy }}
                <button input="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </form>
        </div>
        <div class="meeting-card-holder">
        {% for meeting in object_list %}
        <div class="meeting-card">
            <div class="meeting-header">
                <h4 style="color:teal">{{ meeting.name }}</h4>
                <div class="del-editicons">
                    <a href="{% url 'meeting:meeting_update' slug=meeting.slug %}"><i class="bi bi-pencil-square"></i></a></span>
                    <a href="{% url 'meeting:meeting_delete' slug=meeting.slug %} "><i style="color: red;" class="bi bi-trash"></i></a>
                </div>
            </div>
            <p>{{ meeting.theme }}</p>
            <div class="date-tag">
                <small style="font-size: 10px; margin-right: 20px; font-weight: bold;">{{ meeting.dateScheduled }}</small>
                <a style="text-decoration:unset;" href="{% url 'meeting:agenda_list' slug=meeting.slug %}"><button class="btn btn-primary">Join</button></a>
            </div>
        </div>
        {% empty %}
            <h5 class="text-danger p-5">Meeting not found</h5>
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

meeting/templates/meeting/meeting_update.html
{% extends "index.html" %}
{% block title %}Update meeting{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    color: teal;
    font-weight: bold;
    }

</style>

<div class="container form-container">
    <h3 class="mt-3 mb-3">Update meeting</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">update meeting</button>
    </form>
</div>
{% endblock %}

meeting/templates/meeting/minutes_view.html
{% extends "index.html" %}
{% block title %}Minutes{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<style>
    .form-container{
    margin-top: 100px;
    }

    .btnu{
    margin: auto;
    width: 50%;
    display: flex;
    justify-content: center;
    }

    label{
    display: none;
    }

</style>

<div class="container form-container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3 btnu">submit minutes</button>
    </form>
</div>
{% endblock %}