eboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meeting.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

meeting/urls.py
from django.urls import path
from .views import MeetingsView,UpdateMeetingView, UpdateAgendaView, UpdateDocumentView, AgendasView,CreateAgendaView,CreateDocumentView, CreateMinutesView, UpdateMinutesView, DeleteAgendaView,DeleteDocumentView,DeleteMeetingView, CreateMeetingView

app_name="meeting"
urlpatterns = [
    path('', MeetingsView.as_view(), name='meeting_list'),
    path('add-board/', CreateMeetingView.as_view(), name='meeting_create'),
    path('<str:slug>/', AgendasView.as_view(), name='agenda_list'),
    path('<str:slug>/update-board/', UpdateMeetingView.as_view(), name='meeting_update'),
    path('<str:slug>/delete-board/', DeleteMeetingView.as_view(), name='meeting_delete'),
    path('<str:slug>/minutes/', CreateMinutesView.as_view(), name='minutes_page'),
    path('<str:slug>/agenda/', CreateAgendaView.as_view(), name='agenda_create'),
    path('<str:slug>/document/', CreateDocumentView.as_view(), name='document_create'),
    path('<str:meeting>/<str:slug>/update-minutes/', UpdateMinutesView.as_view(), name='minutes_update'),
    path('<str:meeting>/<str:slug>/update-agenda/', UpdateAgendaView.as_view(), name='agenda_update'),
    path('<str:meeting>/<str:slug>/update-document/', UpdateDocumentView.as_view(), name='document_update'),
    path('<str:meeting>/<str:slug>/delete-agenda/', DeleteAgendaView.as_view(), name='agenda_delete'),
    path('<str:meeting>/<str:slug>/delete-document/', DeleteDocumentView.as_view(), name='document_delete'),
]

templates/footer.html
<style>
    footer{
    bottom: 0;
    width: 100%;
    border-top: 1px solid #ccc;
    margin-top: 10px;
    }
</style>
<footer>
    <h4 class="p-5 d-flex justify-content-center">&copy;Ambrose 2022 </h4>
</footer>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'files/images/meetingpng.png' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css" integrity="sha512-Oy+sz5W86PK0ZIkawrG0iv7XwWhYecM3exvUtMKNJMekGFJtVAhibhRPTpmyTj8+lJCkmWfnpxKgT2OopquBHA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title %}{% endblock %}</title>
</head>
<style>
	.navimg{
	height: 40px;
	width: 40px;
	padding-right: 5px;
	}



    body::{
    display: block;
    content: "";
    height: 60px;
    }
    body{
    font-family: 'Playfair Display';
    }

    @media(max-width: 760px){
    .logo-title{
    font-size: 15px;
    }
    }

    @media(max-width: 360px){
    .navimg{
	height: 30px;
	width: 30px;
	padding-right: 3px;
	}
    .logo-title{
    display: none;
    }
    }
</style>
<body>
<nav class="topnav navbar navbar-expand-lg navbar-light bg-warning fixed-top">
	{% load static %}
	<div class="container d-flex">
		<a class="navbar-brand" href="{% url 'meeting:meeting_list' %}"><img class="navimg" src="{% static 'files/images/meetingpng.png' %}" /><strong class="logo-title">E-MEETING</strong></a>
		{% block navbutton %}{% endblock %}
	</div>
</nav>

{% block content %}
{% endblock %}

{% include 'footer.html' %}
<script src="{% static 'bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/navbar.html
<style>
	img{
	height: 40px;
	width: 40px;
	padding-right: 5px;
	}

	.add-board{
	margin-left: 5px;
	}

	.add-board{

	}
</style>

<nav class="topnav navbar navbar-expand-lg navbar-light bg-warning fixed-top">
	{% load static %}
	<div class="container">
		<a class="navbar-brand" href="{% url 'meeting:meeting_list' %}"><img src="{% static 'files/images/meetingpng.png' %}" /><strong>E-BOARD</strong></a>
		<a class="navbar-brand text-light btn btn-success add-link" href="{% url 'meeting:meeting_create' %}"><i class="bi bi-plus-square"></i><small class="text-dark add-board">Add Board</small></a>
	</div>
</nav>